### PR TITLE
Wip adjust tabs

### PR DESCRIPTION
**Pull request by mrerrormessage**
Grows/shrinks, with some cool transitions (done on a separate commit for easy removal, if not desired).
screen shot 2015-08-07 at 10 39 27 am
screen shot 2015-08-07 at 10 39 21 am

### CODE REVIEW

**Comment by mrerrormessage** [comment]
@TheBizzle , made the requested corrections. It's working just fine in Safari, Chrome, FF (Safari required the `webkit-` prefix). IE11 works functionally, but the arrows don't appear on the right side (apparently svg data-uri's in css don't work in IE). I don't think this is too much of a problem, but if you disagree, I can work on it a bit more.

**Comment by TheBizzle** [comment]
Can you just drop the arrows in as base64-encoding images, like the NetLogo icon is?

**Comment by mrerrormessage** [comment]
yeah, I'll do that.

**Comment by Idloj** [comment]
You can use Unicode arrows

**Pull request merged**
