### PR TITLE
Default to random model

### PR DESCRIPTION
**Pull request by qiemem**
Current list:

- Sample Models/Art/Follower
- Sample Models/Biology/Wolf Sheep Predation
- Sample Models/Biology/Ants
- Sample Models/Biology/Flocking
- Sample Models/Biology/Virus
- Sample Models/Biology/Daisyworld
- Sample Models/Biology/Evolution/Cooperation
- Sample Models/Computer Science/Cellular Automata/CA 1D Elementary
- Sample Models/Computer Science/Cellular Automata/Life Turtle-Based
- Sample Models/Earth Science/Fire
- Sample Models/Earth Science/Climate Change
- Sample Models/Mathematics/Mousetraps
- Sample Models/Mathematics/3D Solids
- Sample Models/Networks/Preferential Attachment
- Sample Models/Social Science/Voting
- Sample Models/Social Science/Segregation
- Sample Models/Social Science/Traffic Basic
- Sample Models/Chemistry & Physics/Diffusion Limited Aggregation/DLA
- Sample Models/Chemistry & Physics/Ising
- Sample Models/Chemistry & Physics/GasLab/GasLab Adiabatic Piston
- Sample Models/Chemistry & Physics/Heat/Boiling
- Sample Models/Chemistry & Physics/Waves/Wave Machine

Very open to other suggestions. I was hoping to have more cellular models like B-Z reaction, but decided they were too slow. I didn't put Termites because the way it's written is really expecting continuous display updates (the termites can move for an arbitrary amount of time with each `ask`). 

Should the chooser show the randomly selected model? If the answer is yes, we should realign the selected item in the chooser so that you can actually see the model name, instead of just the category. I couldn't get this to work after messing around for a few minutes.

### CODE REVIEW

**Comment by TheBizzle** [comment]
> Should the chooser show the randomly selected model?

Yes.

**Comment by TheBizzle** [comment]
This relates to #270

**Comment by qiemem** [comment]
> > Should the chooser show the randomly selected model?

> Yes.

Alright, did what I could.

**Comment by SethTisue** [comment]
some additional suggestions: Slime, Erosion, Team Assembly, Virus on a Network

**Comment by TheBizzle** [comment]
@SethTisue, thanks for the suggestions.  I've had the models you listed in  7d5bce315fa9717c64126361fed40c8f4cff3408.

**Comment by qiemem** [comment]
Virus on a network looks really weird because of the large link arrows. Slime is pretty slow.

**Comment by TheBizzle** [comment]
Virus on a Network doesn't use directed links.  You must be thinking of a different model.

Slime runs in about the same time per tick as Voting (a model from your list).  Personally, I think both look fine/run fast enough to be demoable.

**Comment by qiemem** [comment]
Oh I was thinking of diffusion on a network. Sorry about that!

**Pull request merged**
