### PR TITLE
Fix line widths

### PR DESCRIPTION
**Pull request by qiemem**
This ignores the shape cache. We can bring that back if necessary.

### CODE REVIEW

**Comment by qiemem** [comment]
This also fixes #221.

Not sure why Travis is failing. I didn't change anything server-side.

**Comment by TheBizzle** [comment]
Sometimes Travis just needs a little bit of this:

Fonzie hitting jukebox

**Comment by qiemem** [comment]
Well then, I guess this is ready.

**Comment by qiemem** [comment]
Take it for a spin, @TheBizzle. See how the performance feels to you. I know there's a significant performance hit (the degree depends on lots of factors: number of turtles (of course), shape, size, and so forth), but the frame skipping keep things tolerable at least.

To disable frame skipping, you can run `session.drawEveryFrame = true`

**Pull request merged**
