### PR TITLE
Add a custom 404 page. closes #276

### LINKED ISSUE #276: NLW Error Pages
We can customize errors for any / all of these pages. We can build one error page and use it everywhere, or build pages for specific errors. A common practice I've seen is having a 404 page, then a separate page for all other errors, but we could also use just one page "Something went wrong..." or something like that.
screen shot 2015-07-24 at 12 33 52 pm

### PR DESCRIPTION
**Pull request by Idloj**

### CODE REVIEW

**Comment by Idloj** [comment]
I understand that Amazon lets you customize the error page like @mrerrormessage mentioned, I did it through Play, so you probably want to extract just the html file and use that.

**Comment by TheBizzle** [comment]
[Import style](https://github.com/NetLogo/NetLogo/wiki/Code-formatting#import-style)
[Missing newline at end of file](https://github.com/NetLogo/NetLogo/wiki/Code-formatting#whitespace)

**Comment by mrerrormessage** [comment]
Please add a route to generate the 404 page to `scrapeRoutes` in build.sbt, per my comment on [this PR](https://github.com/NetLogo/Galapagos/pull/277#issuecomment-125192763). Something like `"/404"` would be ideal.

**Comment by Idloj** [comment]
Um, what exactly do I need to do? (I just went after the instructions of Play)

**Comment by Idloj** [comment]
(The tree import style is super inconvenient. I did it just for you, @TheBizzle)

**Comment by TheBizzle** [comment]
You might also find it incredibly inconvenient one day to be have massive compile times in a big project, or find yourself perpetually confused as to which version of `List` is being used in a particular file, only to eventually discover that wildcard imports were making your life substantially worse.

**Comment by Idloj** [comment]
I'm in your opinion about wildcards too, I was just talking about the tree

**Comment by TheBizzle** [comment]
Travis failed on your branch.  Here's what it had to say:

> [info] scalastyle using config /home/travis/build/NetLogo/Galapagos/scalastyle-config.xml
> [error] /home/travis/build/NetLogo/Galapagos/app/ErrorHandler.scala:1: Header does not match expected text
> [error] /home/travis/build/NetLogo/Galapagos/app/ErrorHandler.scala:23:15: Public method must have explicit type

The "header" message refers to [this](https://github.com/NetLogo/Galapagos/blob/master/app/controllers/Application.scala#L1), which, due to our license, must be included at the top of each file.

**Comment by TheBizzle** [comment]
In cd4331427df8776c50bbc030b42ab34a3a2dd81b, @mrerrormessage devised a 404 page that we ended up liking more, so I'm going to close this PR without merging.  Sorry that we weren't able to incorporate your work here.

**Pull request closed without merging**
