### PR TITLE
Widget fixes

### PR DESCRIPTION
**Pull request by qiemem**
Not sure how exactly to bundle fixes for #269. These should probably be merged in on their own as the other fixes are somewhat more complicated.

### CODE REVIEW

**Comment by qiemem** [comment]
@TheBizzle I believe this is ready for review and merge. If there's any other widget fixes you'd like to see in here first, let me know. If you'd prefer the action keys thing in its own PR, I can do that too.

**Comment by TheBizzle** [comment]
If you check out Minesweeper in 5e4709a55116db4f35f4d48e60fc3f659f7c0002 (the commit that adds "action keys"), you'll see that the text for the "setup" and "mark" buttons is left-aligned, where it should be centered like the text for "go" is.  The button text is properly centered for all buttons when using the code from the commit before.  @qiemem, please resolve this, and rebase onto `master` before resubmitting.

**Comment by TheBizzle** [comment]
Note that I only seem to be able to reproduce this behavior in Opera (30.0.1835.125), but not in Firefox or Chrome.

**Comment by qiemem** [comment]
I was also able to reproduce it Safari and, oddly, Opera after I updated
it. Should be fixed now.

**Pull request closed without merging**
