### PR TITLE
Upgrade sbt, play-scrape

### PR DESCRIPTION
**Pull request by mrerrormessage**
Somehow beat @SethTisue to the sbt version bump. Ordinarily, I would check this into master, but with the number of PRs/merges going on at the moment, I didn't want to interrupt by pushing to master unexpectedly.

### CODE REVIEW

**Comment by TheBizzle** [comment]
Judging by the looks of [this](https://github.com/scalastyle/scalastyle/issues/152), the new SBT version is what's responsible for the error we're getting when we run Scalastyle, so I don't think I can accept the SBT version upgrade at the moment.

The one time someone other than Seth updates SBT versions, the SBT release is broken.  Coincidence?  I think not!

**Comment by mrerrormessage** [comment]
Yeah, we definitely need Seth to upgrade.

**Comment by SethTisue** [comment]
I actually inserted a bug in 2.10.5 back in March exactly to lay the groundwork for this triumphant moment

**Comment by TheBizzle** [comment]
Newman!

Tisue...!

**Comment by SethTisue** [comment]
I think this just needs this workaround: https://github.com/scalastyle/scalastyle/issues/156#issuecomment-137229733

**Comment by SethTisue** [comment]
a new release of Scalastyle is out that doesn't have this bug

**Comment by TheBizzle** [comment]
Closing.  Supplanted by d0c0fc3d3b39e8406a53706459297a45d94dda45

**Pull request closed without merging**
