### PR TITLE
Follow!

### PR DESCRIPTION
**Pull request by qiemem**
Everything should work: follow wrapping, spotlight, mouse stuff (including updating position when follow wrapping changes mouse screen position does not).

Waiting to squash till end of review.

### CODE REVIEW

**Comment by qiemem** [comment]
I should note: this does *not* include the great refactor I'd been working on. Decided it wasn't worth it, though the repeated wrapping logic still bugs me.

**Comment by TheBizzle** [comment]
Please rebase onto `master`.

**Comment by qiemem** [comment]
@skorlir This PR includes the refactor we talked about. [`usePatchCoordinates`](https://github.com/NetLogo/Galapagos/pull/231/files#diff-93679edcf7457bb5eee16a45da9d5870R96) should wrap drawing code that wants to draw in patch coordinates. [Turtle and link drawing now uses it for instance.](https://github.com/NetLogo/Galapagos/pull/231/files#diff-93679edcf7457bb5eee16a45da9d5870R96) The view is now untransformed by default, so [untransformation code is no longer necessary](https://github.com/NetLogo/Galapagos/pull/231/files#diff-93679edcf7457bb5eee16a45da9d5870R96).

**Comment by TheBizzle** [comment]
@qiemem, is there more on the way, or is this ready for my review now?

**Comment by skorlir** [comment]
@qiemem This is good, because I no longer have to do untransformations, but I can't use `usePatchCoordinates` because it transforms the view context, and I'm drawing the to drawingLayer. Is there any reason to not just refactor `usePatchCoordinates` to accept a context as its argument?

Using `usePatchCoordinates` only when stamping the canvas is no good (I went ahead and tried just to be sure); I end up with the exact problem I had before where I can't scale things correctly. I need to be able to use the transform for patch coordinates separately from the view's drawing context.

**Comment by qiemem** [comment]
Good point, I'll tweak it.

**Comment by skorlir** [comment]
Aacctually you might not want to. I tried that, and this had the scaling
problem I had before. I was able to get things working on wip-pen-trails
yesterday by reverse-engineering a "PatchCorsToPixels" function and using
that instead. It feels kinda weird to be passing the drawing context for an
invisible canvas to the view anyway, and `usePatchCoordinates` works well
in functions using the view canvas (although its name is a little
misleading). I dunno. Check out the branch and let me know what you think.

**Comment by qiemem** [comment]
Hmm, okay. We should meet to talk about this scaling issue.

**Comment by qiemem** [comment]
@TheBizzle Hold off until @skorlir and I talk.

**Comment by qiemem** [comment]
So squashed.

**Pull request merged**
