### PR TITLE
version bumps

### PR DESCRIPTION
**Pull request by SethTisue**
[Review on Reviewable](https://reviewable.io/reviews/netlogo/galapagos/194)

### CODE REVIEW

**Comment by SethTisue** [comment]
hmm. I don't understand why the tortoise artifact isn't resolving.

**Comment by TheBizzle** [comment]
I'll take care of fixing the resolution issue.

**Comment by TheBizzle** [comment]
As far as I can tell, the problem is sbt/sbt#1820.

**Comment by TheBizzle** [comment]
For the time being, I've switched to some BinTray repositories that don't mirror to JCenter (to avoid having Typesafe Releases block us from getting our artifacts).  With that, everything works fine again.  Hopefully one day we can go back to putting our artifacts on JCenter.  (But that day is not today.)

**Pull request merged**
